### ISSUE TITLE
Allow route creation

### ISSUE THREAD

**Issue by zackharley** [zackharley/QHacks#4]

**Comment by Jalsemgeest** [comment]
Do we want this to have a user provide what 'routes' they want and then we create them?

**Comment by zackharley** [comment]
We could do that. Or would it be easier to just create an example route?

**Comment by Jalsemgeest** [comment]
I think if we offered it we would auto-include the express and modules needed.  Then offer an input with comma separated values.

Do you want routes? checkbox (revealing a input if checked)
Input box with placeholder: "Input routes wanted separated by commas"
Then we generate the routes.

**Comment by zackharley** [comment]
Okay. Also, we should auto-include Express right?

**Comment by zackharley** [comment]
I like that. I think the more we can help the user create, the better our tool will be.

**Comment by Jalsemgeest** [comment]
Exactly.
